//
//  Regions.swift
//  Cinemate
//
//  Created by YUDONG LU on 17/9/2025.
//

import Foundation

/* ISO_3166_1 */
enum Regions : String, Codable, Identifiable, CaseIterable {
    case Andorra = "AD"
    case UnitedArabEmirates = "AE"
    case AntiguaBarbuda = "AG"
    case Albania = "AL"
    case Angola = "AO"
    case Argentina = "AR"
    case Austria = "AT"
    case Australia = "AU"
    case Azerbaijan = "AZ"
    case BosniaHerzegovina = "BA"
    case Barbados = "BB"
    case Belgium = "BE"
    case BurkinaFaso = "BF"
    case Bulgaria = "BG"
    case Bahrain = "BH"
    case Bermuda = "BM"
    case Bolivia = "BO"
    case Brazil = "BR"
    case Bahamas = "BS"
    case Belarus = "BY"
    case Belize = "BZ"
    case Canada = "CA"
    case DemocraticRepublicoftheCongoKinshasa = "CD"
    case Switzerland = "CH"
    case CtedIvoire = "CI"
    case Chile = "CL"
    case Cameroon = "CM"
    case Colombia = "CO"
    case CostaRica = "CR"
    case Cuba = "CU"
    case CapeVerde = "CV"
    case Cyprus = "CY"
    case CzechRepublic = "CZ"
    case Germany = "DE"
    case Denmark = "DK"
    case DominicanRepublic = "DO"
    case Algeria = "DZ"
    case Ecuador = "EC"
    case Estonia = "EE"
    case Egypt = "EG"
    case Spain = "ES"
    case Finland = "FI"
    case Fiji = "FJ"
    case France = "FR"
    case UnitedKingdom = "GB"
    case FrenchGuiana = "GF"
    case Ghana = "GH"
    case Gibraltar = "GI"
    case Guadeloupe = "GP"
    case EquatorialGuinea = "GQ"
    case Greece = "GR"
    case Guatemala = "GT"
    case Guyana = "GY"
    case HongKongSARChina = "HK"
    case Honduras = "HN"
    case Croatia = "HR"
    case Hungary = "HU"
    case Indonesia = "ID"
    case Ireland = "IE"
    case Israel = "IL"
    case India = "IN"
    case Iraq = "IQ"
    case Iceland = "IS"
    case Italy = "IT"
    case Jamaica = "JM"
    case Jordan = "JO"
    case Japan = "JP"
    case Kenya = "KE"
    case SouthKorea = "KR"
    case Kuwait = "KW"
    case Lebanon = "LB"
    case StLucia = "LC"
    case Liechtenstein = "LI"
    case Lithuania = "LT"
    case Luxembourg = "LU"
    case Latvia = "LV"
    case Libya = "LY"
    case Morocco = "MA"
    case Monaco = "MC"
    case Moldova = "MD"
    case Montenegro = "ME"
    case Madagascar = "MG"
    case Macedonia = "MK"
    case Mali = "ML"
    case Malta = "MT"
    case Mauritius = "MU"
    case Malawi = "MW"
    case Mexico = "MX"
    case Malaysia = "MY"
    case Mozambique = "MZ"
    case Niger = "NE"
    case Nigeria = "NG"
    case Nicaragua = "NI"
    case Netherlands = "NL"
    case Norway = "NO"
    case NewZealand = "NZ"
    case Oman = "OM"
    case Panama = "PA"
    case Peru = "PE"
    case FrenchPolynesia = "PF"
    case PapuaNewGuinea = "PG"
    case Philippines = "PH"
    case Pakistan = "PK"
    case Poland = "PL"
    case PalestinianTerritories = "PS"
    case Portugal = "PT"
    case Paraguay = "PY"
    case Qatar = "QA"
    case Romania = "RO"
    case Serbia = "RS"
    case Russia = "RU"
    case SaudiArabia = "SA"
    case Seychelles = "SC"
    case Sweden = "SE"
    case Singapore = "SG"
    case Slovenia = "SI"
    case Slovakia = "SK"
    case SanMarino = "SM"
    case Senegal = "SN"
    case ElSalvador = "SV"
    case TurksCaicosIslands = "TC"
    case Chad = "TD"
    case Thailand = "TH"
    case Tunisia = "TN"
    case Turkey = "TR"
    case TrinidadTobago = "TT"
    case Tanzania = "TZ"
    case Ukraine = "UA"
    case Uganda = "UG"
    case UnitedStates = "US"
    case Uruguay = "UY"
    case VaticanCity = "VA"
    case Venezuela = "VE"
    case Kosovo = "XK"
    case Yemen = "YE"
    case SouthAfrica = "ZA"
    case Zambia = "ZM"
    
    var id: String { self.rawValue }
    
    var label: String {
        switch self {
        case .Andorra: return "Andorra"
        case .UnitedArabEmirates: return "United Arab Emirates"
        case .AntiguaBarbuda: return "Antigua & Barbuda"
        case .Albania: return "Albania"
        case .Angola: return "Angola"
        case .Argentina: return "Argentina"
        case .Austria: return "Austria"
        case .Australia: return "Australia"
        case .Azerbaijan: return "Azerbaijan"
        case .BosniaHerzegovina: return "Bosnia & Herzegovina"
        case .Barbados: return "Barbados"
        case .Belgium: return "Belgium"
        case .BurkinaFaso: return "Burkina Faso"
        case .Bulgaria: return "Bulgaria"
        case .Bahrain: return "Bahrain"
        case .Bermuda: return "Bermuda"
        case .Bolivia: return "Bolivia"
        case .Brazil: return "Brazil"
        case .Bahamas: return "Bahamas"
        case .Belarus: return "Belarus"
        case .Belize: return "Belize"
        case .Canada: return "Canada"
        case .DemocraticRepublicoftheCongoKinshasa: return "Democratic Republic of the Congo"
        case .Switzerland: return "Switzerland"
        case .CtedIvoire: return "Côte d'Ivoire"
        case .Chile: return "Chile"
        case .Cameroon: return "Cameroon"
        case .Colombia: return "Colombia"
        case .CostaRica: return "Costa Rica"
        case .Cuba: return "Cuba"
        case .CapeVerde: return "Cape Verde"
        case .Cyprus: return "Cyprus"
        case .CzechRepublic: return "Czech Republic"
        case .Germany: return "Germany"
        case .Denmark: return "Denmark"
        case .DominicanRepublic: return "Dominican Republic"
        case .Algeria: return "Algeria"
        case .Ecuador: return "Ecuador"
        case .Estonia: return "Estonia"
        case .Egypt: return "Egypt"
        case .Spain: return "Spain"
        case .Finland: return "Finland"
        case .Fiji: return "Fiji"
        case .France: return "France"
        case .UnitedKingdom: return "United Kingdom"
        case .FrenchGuiana: return "French Guiana"
        case .Ghana: return "Ghana"
        case .Gibraltar: return "Gibraltar"
        case .Guadeloupe: return "Guadeloupe"
        case .EquatorialGuinea: return "Equatorial Guinea"
        case .Greece: return "Greece"
        case .Guatemala: return "Guatemala"
        case .Guyana: return "Guyana"
        case .HongKongSARChina: return "Hong Kong"
        case .Honduras: return "Honduras"
        case .Croatia: return "Croatia"
        case .Hungary: return "Hungary"
        case .Indonesia: return "Indonesia"
        case .Ireland: return "Ireland"
        case .Israel: return "Israel"
        case .India: return "India"
        case .Iraq: return "Iraq"
        case .Iceland: return "Iceland"
        case .Italy: return "Italy"
        case .Jamaica: return "Jamaica"
        case .Jordan: return "Jordan"
        case .Japan: return "Japan"
        case .Kenya: return "Kenya"
        case .SouthKorea: return "South Korea"
        case .Kuwait: return "Kuwait"
        case .Lebanon: return "Lebanon"
        case .StLucia: return "St. Lucia"
        case .Liechtenstein: return "Liechtenstein"
        case .Lithuania: return "Lithuania"
        case .Luxembourg: return "Luxembourg"
        case .Latvia: return "Latvia"
        case .Libya: return "Libya"
        case .Morocco: return "Morocco"
        case .Monaco: return "Monaco"
        case .Moldova: return "Moldova"
        case .Montenegro: return "Montenegro"
        case .Madagascar: return "Madagascar"
        case .Macedonia: return "North Macedonia"
        case .Mali: return "Mali"
        case .Malta: return "Malta"
        case .Mauritius: return "Mauritius"
        case .Malawi: return "Malawi"
        case .Mexico: return "Mexico"
        case .Malaysia: return "Malaysia"
        case .Mozambique: return "Mozambique"
        case .Niger: return "Niger"
        case .Nigeria: return "Nigeria"
        case .Nicaragua: return "Nicaragua"
        case .Netherlands: return "Netherlands"
        case .Norway: return "Norway"
        case .NewZealand: return "New Zealand"
        case .Oman: return "Oman"
        case .Panama: return "Panama"
        case .Peru: return "Peru"
        case .FrenchPolynesia: return "French Polynesia"
        case .PapuaNewGuinea: return "Papua New Guinea"
        case .Philippines: return "Philippines"
        case .Pakistan: return "Pakistan"
        case .Poland: return "Poland"
        case .PalestinianTerritories: return "Palestinian Territories"
        case .Portugal: return "Portugal"
        case .Paraguay: return "Paraguay"
        case .Qatar: return "Qatar"
        case .Romania: return "Romania"
        case .Serbia: return "Serbia"
        case .Russia: return "Russia"
        case .SaudiArabia: return "Saudi Arabia"
        case .Seychelles: return "Seychelles"
        case .Sweden: return "Sweden"
        case .Singapore: return "Singapore"
        case .Slovenia: return "Slovenia"
        case .Slovakia: return "Slovakia"
        case .SanMarino: return "San Marino"
        case .Senegal: return "Senegal"
        case .ElSalvador: return "El Salvador"
        case .TurksCaicosIslands: return "Turks & Caicos Islands"
        case .Chad: return "Chad"
        case .Thailand: return "Thailand"
        case .Tunisia: return "Tunisia"
        case .Turkey: return "Turkey"
        case .TrinidadTobago: return "Trinidad & Tobago"
        case .Tanzania: return "Tanzania"
        case .Ukraine: return "Ukraine"
        case .Uganda: return "Uganda"
        case .UnitedStates: return "United States"
        case .Uruguay: return "Uruguay"
        case .VaticanCity: return "Vatican City"
        case .Venezuela: return "Venezuela"
        case .Kosovo: return "Kosovo"
        case .Yemen: return "Yemen"
        case .SouthAfrica: return "South Africa"
        case .Zambia: return "Zambia"
        }
    }

    func convertISOToNationalFlag() -> String {
        let base: UInt32 = 127397
        var scalarView = String.UnicodeScalarView()
        for scalar in self.rawValue.uppercased().unicodeScalars {
            if let scalarFlag = UnicodeScalar(base + scalar.value) {
                scalarView.append(scalarFlag)
            }
        }
        return String(scalarView)
    }
}
