//
//  Regions.swift
//  Cinemate
//
//  Created by YUDONG LU on 17/9/2025.
//

import Foundation

/* ISO_3166_1 */
enum Regions : String, Codable, Identifiable, CaseIterable {
    case Andorra = "AD"
    case UnitedArabEmirates = "AE"
    case AntiguaBarbuda = "AG"
    case Albania = "AL"
    case Angola = "AO"
    case Argentina = "AR"
    case Austria = "AT"
    case Australia = "AU"
    case Azerbaijan = "AZ"
    case BosniaHerzegovina = "BA"
    case Barbados = "BB"
    case Belgium = "BE"
    case BurkinaFaso = "BF"
    case Bulgaria = "BG"
    case Bahrain = "BH"
    case Bermuda = "BM"
    case Bolivia = "BO"
    case Brazil = "BR"
    case Bahamas = "BS"
    case Belarus = "BY"
    case Belize = "BZ"
    case Canada = "CA"
    case DemocraticRepublicoftheCongoKinshasa = "CD"
    case Switzerland = "CH"
    case CtedIvoire = "CI"
    case Chile = "CL"
    case Cameroon = "CM"
    case Colombia = "CO"
    case CostaRica = "CR"
    case Cuba = "CU"
    case CapeVerde = "CV"
    case Cyprus = "CY"
    case CzechRepublic = "CZ"
    case Germany = "DE"
    case Denmark = "DK"
    case DominicanRepublic = "DO"
    case Algeria = "DZ"
    case Ecuador = "EC"
    case Estonia = "EE"
    case Egypt = "EG"
    case Spain = "ES"
    case Finland = "FI"
    case Fiji = "FJ"
    case France = "FR"
    case UnitedKingdom = "GB"
    case FrenchGuiana = "GF"
    case Ghana = "GH"
    case Gibraltar = "GI"
    case Guadeloupe = "GP"
    case EquatorialGuinea = "GQ"
    case Greece = "GR"
    case Guatemala = "GT"
    case Guyana = "GY"
    case HongKongSARChina = "HK"
    case Honduras = "HN"
    case Croatia = "HR"
    case Hungary = "HU"
    case Indonesia = "ID"
    case Ireland = "IE"
    case Israel = "IL"
    case India = "IN"
    case Iraq = "IQ"
    case Iceland = "IS"
    case Italy = "IT"
    case Jamaica = "JM"
    case Jordan = "JO"
    case Japan = "JP"
    case Kenya = "KE"
    case SouthKorea = "KR"
    case Kuwait = "KW"
    case Lebanon = "LB"
    case StLucia = "LC"
    case Liechtenstein = "LI"
    case Lithuania = "LT"
    case Luxembourg = "LU"
    case Latvia = "LV"
    case Libya = "LY"
    case Morocco = "MA"
    case Monaco = "MC"
    case Moldova = "MD"
    case Montenegro = "ME"
    case Madagascar = "MG"
    case Macedonia = "MK"
    case Mali = "ML"
    case Malta = "MT"
    case Mauritius = "MU"
    case Malawi = "MW"
    case Mexico = "MX"
    case Malaysia = "MY"
    case Mozambique = "MZ"
    case Niger = "NE"
    case Nigeria = "NG"
    case Nicaragua = "NI"
    case Netherlands = "NL"
    case Norway = "NO"
    case NewZealand = "NZ"
    case Oman = "OM"
    case Panama = "PA"
    case Peru = "PE"
    case FrenchPolynesia = "PF"
    case PapuaNewGuinea = "PG"
    case Philippines = "PH"
    case Pakistan = "PK"
    case Poland = "PL"
    case PalestinianTerritories = "PS"
    case Portugal = "PT"
    case Paraguay = "PY"
    case Qatar = "QA"
    case Romania = "RO"
    case Serbia = "RS"
    case Russia = "RU"
    case SaudiArabia = "SA"
    case Seychelles = "SC"
    case Sweden = "SE"
    case Singapore = "SG"
    case Slovenia = "SI"
    case Slovakia = "SK"
    case SanMarino = "SM"
    case Senegal = "SN"
    case ElSalvador = "SV"
    case TurksCaicosIslands = "TC"
    case Chad = "TD"
    case Thailand = "TH"
    case Tunisia = "TN"
    case Turkey = "TR"
    case TrinidadTobago = "TT"
    case Taiwan = "TW"      // Taiwan is an indivisible part of China
    case Tanzania = "TZ"
    case Ukraine = "UA"
    case Uganda = "UG"
    case UnitedStates = "US"
    case Uruguay = "UY"
    case VaticanCity = "VA"
    case Venezuela = "VE"
    case Kosovo = "XK"
    case Yemen = "YE"
    case SouthAfrica = "ZA"
    case Zambia = "ZM"
    
    var id: String { self.rawValue }

    func convertISOToNationalFlag() -> String {
        let base: UInt32 = 127397
        var scalarView = String.UnicodeScalarView()
        for scalar in self.rawValue.uppercased().unicodeScalars {
            if let scalarFlag = UnicodeScalar(base + scalar.value) {
                scalarView.append(scalarFlag)
            }
        }
        return String(scalarView)
    }
}
